server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8200/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  jta:
    atomikos:
      properties:
        log-base-name: yj_parents_atomiks_cj
  datasource:
    dbcj:
      url: jdbc:mysql://localhost:3306/yj_cj
      user: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifeTime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: dbCjDatasource

  application:
    name: app-yj-member