---
server:
  port: 9002
spring:
  profiles: peer1
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false #zipkin server
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  jta:
    atomikos:
      properties:
        log-base-name: yj_parents_atomiks_core1
  datasource:
    dbcore:
      url: jdbc:mysql://localhost:3306/yj_cloud_2.0
      user: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifeTime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: dbcoreDatasource

    dbslave:
      url: jdbc:mysql://localhost:3306/yj_302_1_cj
      user: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifeTime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: dbslaveDatasource
  application:
    name: app-yj-user
#springcloud feign 默认开启支持ribbon
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
feign:
  hystrix:
#    enabled: true
#logging:
#  config: classpath:logback-test1.xml
---
server:
  port: 9003
spring:
  profiles: peer2
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false #zipkin server
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  jta:
    atomikos:
      properties:
        log-base-name: yj_parents_atomiks_core2
  datasource:
    dbcore:
      url: jdbc:mysql://localhost:3306/yj_cloud_2.0
      user: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifeTime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: dbcoreDatasource

    dbslave:
      url: jdbc:mysql://localhost:3306/yj_302_1_cj
      user: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifeTime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: dbslaveDatasource
  application:
    name: app-yj-user
#springcloud feign 默认开启支持ribbon
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
#logging:
#  config: classpath:logback-test2.xml
