server:
  port: 8080
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 4 #每隔这个时间会主动心跳一次 默认值为30s，更新自己的状态
#    lease-expiration-duration-in-seconds: 12 #设置服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8200/eureka/
#    register-with-eureka: true
#    fetch-registry: true
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false #zipkin server
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: app-yj-ui
logging:
  config: classpath:logback-test1.xml
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
gateway:
  ip: 127.0.0.1
  port: 7000