server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8200/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: app-yj-ui
#ribbon:
#  ReadTimeout:  5000
#  ConnectTimeout: 5000
#feign:
#  hystrix:
#    enabled: true