server:
  port: 8080
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false #zipkin server
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: app-yj-ui
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
#feign:
#  hystrix:
#    enabled: true
gateway:
  ip: 127.0.0.1
  port: 7000
logging:
  level:
    com.yj.ui.feign.IUserServiceFeign: debug