---
server:
  port: 7000
spring:
  profiles: peer1
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: app-yj-core
        uri: lb://app-yj-core
        predicates:
        - Path=/app-yj-core/**
      - id: app-yj-member
        uri: lb://app-yj-member
        predicates:
        - Path=/app-yj-member/**
      #开启服务名发现，根据服务名转发，实现负载均衡
      discovery:
        locator:
          enabled: true


#----------------------------------------
---
server:
  port: 7001
spring:
  profiles: peer2
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: app-yj-core
        uri: lb://app-yj-core
        predicates:
        - Path=/app-yj-core/**
      - id: app-yj-member
        uri: lb://app-yj-member
        predicates:
        - Path=/app-yj-member/**
      discovery:
        locator:
          enabled: true

